# Generated by Django 4.1.7 on 2023-04-01 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_control', '0003_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='name',
        ),
    ]
