# Generated by Django 4.1.7 on 2023-04-06 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message_control', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genericfileupload',
            name='file_upload',
            field=models.FileField(upload_to='uploads/'),
        ),
    ]
